version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "JonathanPhillips"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "python"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 3
    reviewers:
      - "JonathanPhillips"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 3
    reviewers:
      - "JonathanPhillips"
    commit-message:
      prefix: "actions"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"