version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: nfl_analysis
      POSTGRES_USER: nfl_user
      POSTGRES_PASSWORD: nfl_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/app/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nfl_user -d nfl_analysis"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://nfl_user:nfl_password@db:5432/nfl_analysis
      - PYTHONPATH=/app
    volumes:
      - ./data:/app/data
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload

  scraper:
    build: .
    environment:
      - DATABASE_URL=postgresql://nfl_user:nfl_password@db:5432/nfl_analysis
      - PYTHONPATH=/app
    volumes:
      - ./data:/app/data
    depends_on:
      db:
        condition: service_healthy
    command: python src/scrapers/scheduler.py
    profiles:
      - scraper

volumes:
  postgres_data: